### ISSUE TITLE
dpad - Question

### ISSUE THREAD

**Issue by GekoCH** [unfoldedcircle/integration-node-library#29]
Hy

I made a new driver to interact with the OpenHAB REST API.
I tried to use the media_player entity since I like to control my kodi setup over OpenHAB. The volume, skip, prev, mute, play_pause buttons do work. However the dpad, the colored buttons as welle as the seek buttons do not react to this function:
`uc.on(uc.EVENTS.ENTITY_COMMAND, async (wsHandle, entityId, entityType, cmdId, params) => {}`

I did add the addEntity with following statement:
```
const entity = new uc.Entities.MediaPlayer(
  "my_media",
  "Media Player",
  [uc.Entities.MediaPlayer.FEATURES.SEEK, uc.Entities.MediaPlayer.FEATURES.TOGGLE, uc.Entities.MediaPlayer.FEATURES.DPAD, uc.Entities.MediaPlayer.FEATURES.ON_OFF, uc.Entities.MediaPlayer.FEATURES.VOLUME]
);
```

What am I mssing here?

Andy

**Comment by zehnm** [comment]
If you added new features to an already configured entity, it needs to be reloaded in Remote Two. Otherwise the new features are not picked up.
Dynamic features (adding & removing on the fly) are not supported at the moment.

**Comment by GekoCH** [comment]
thx reloading the entity did the trick, thx

**Comment by GekoCH** [comment]
thx reloading the entity did the trick, thx
